### ISSUE TITLE
No matching distribution found error

### ISSUE THREAD

**Issue by asujata-1234** [keironstoddart/edi-835-parser#1]
When I am trying to install I keep getting following error.

Could not find a version that satisfies the requirement edi-835-parser
ERROR: No matching distribution found for edi-835-parser

**Comment by keironstoddart** [comment]
Hi there, please note that the package is currently only available for Python 3.9 and higher.

https://github.com/keironstoddart/edi-835-parser/blob/main/setup.py

I will add a sentence to the README to make this explicit.

What version of Python were you using when you tried to install the package? I can work on backward compatibility.

**Comment by asujata-1234** [comment]
I did upgrade python to 3.9.2, I am still getting same error.

![Screen Shot 2021-03-09 at 5 05 25 AM](https://user-images.githubusercontent.com/19535802/110693579-998ab480-81b5-11eb-8a9a-6073d1ae5ef2.png)

**Comment by keironstoddart** [comment]
Thank you for the screenshot, I apologize for the trouble. I have re-uploaded the package to PyPI with broader download requirements. Please try again and let me know if you are still having trouble. Please also make sure you use the latest version of pip.

**Comment by asujata-1234** [comment]
I am still having same issue. I did clone repository and the copied this folder into the path where my anaconda is located.

![image](https://user-images.githubusercontent.com/19535802/111196842-25288a80-8594-11eb-988e-1a68b1d3b46a.png)
