### ISSUE TITLE
IndexError in entity.py

### ISSUE THREAD

**Issue by nsargent22** [keironstoddart/edi-835-parser#20]
Some remittance files contain the 'NM1' segment multiple times in the claim loop. Occasionally the 'NM1' segments contain fewer than 3 elements, which raises an IndexError exception once the segment gets to Entity class in entity.py.

**Comment by gizquier2** [comment]
Please see #2

**Comment by nsargent22** [comment]
From `edi_835_parser.segments.entity`, lines 21 - 23:

`self.entity = get_element(segment, 1)`
`self.type = get_element(segment, 2)`
`self.last_name = get_element(segment, 3)`

Using `get_element` instead of `segment[x]` allowed many of the files which threw IndexError exceptions here to parse normally. I'll create a PR for this soon.
