### ISSUE TITLE
Pandas dataframe enhancement 

### ISSUE THREAD

**Issue by gizquier2** [keironstoddart/edi-835-parser#3]
REF 6R that may help to circle back to 837,
`REF - LINE ITEM CONTROL NUMBER
X12 Segment Name: Reference Information
X12 Purpose: To specify identifying information
X12 Syntax: 1. R0203
At least one of REF02 or REF03 is required.
Loop: 2110 — SERVICE PAYMENT INFORMATION`

Adjustments per service is fundamental in an 835 parser,  instead of closing segments on each ~, may loop from CLP to next CLP and capture the adjustments and the reference.

`CAS - SERVICE ADJUSTMENT
X12 Segment Name: Claims Adjustment
X12 Purpose: To supply adjustment reason codes and amounts as needed for an entire claim
or for a particular service within the claim being paid` may be multiple

**Comment by keironstoddart** [comment]
@gizquier2, thank you again for the great feedback. Your suggestions have been added to v1.3.0 which was just released today.
