### ISSUE TITLE
SVC segment 1 

### ISSUE THREAD

**Issue by gizquier2** [keironstoddart/edi-835-parser#4]
In the parser you are cutting just the middle part of the SVC segment 1

` class ServiceCode(Element):

	def parser(self, value: str) -> str:
		value = split_element(value)
		_, code, *_ = value
		return code `

![image](https://user-images.githubusercontent.com/25261759/115338713-6acb0b00-a171-11eb-85dc-07e20b59dfbe.png)

Probably a good way to do this is sparse this in 3 columns, 1 is the the first part HC ( for CPT HCPC) , part 2 the code itself, part3 the Modifier if HC.

or in a different way, have 3 columns ( HCPC-CPT, -> include here the code if part 1 is HC, PROC_CODE -> here the code ( part 2) if NU or RB, MODIFIER -> here part 3 if HC in part 1)

**Comment by keironstoddart** [comment]
This update is now live. Thank you for your continued support!
