### ISSUE TITLE
CLP Index should not be integer

### ISSUE THREAD

**Issue by gizquier2** [keironstoddart/edi-835-parser#5]
CLP segment 1 should not be an integer, multiple times the claim# or claim identifier, is a "system created value" not only digits.

Easy to solve just change 

class Claim:

	**index = str()**

**Comment by keironstoddart** [comment]
Closed! This update is now live in v1.4.0. @gizquier2, take a look at the README.md file. I added a section to acknowledge your contributions, thank you again for your help! It's really appreciated.
